// Auto-generated by scripts/generate-prompts.ts — DO NOT EDIT
// Regenerate: bun scripts/generate-prompts.ts

export const EMBEDDED_PROMPTS: Record<string, string> = {
  'branch-name-prompt.md': `Generate a SHORT git branch name suffix from this input. Output ONLY the kebab-case suffix (lowercase-with-hyphens), max 2-3 words, 3-25 chars. Be concise — pick the core noun/verb only.

Good: fix-auth, add-cache, user-roles, db-migrate
Bad: add-ai-prompts-and-utils, fix-authentication-module-error, update-user-profile-page
`,
  'commit-message-prompt.md': `Generate a conventional commit message from this git diff. Output ONLY the commit message in this format:

<type>(<scope>): <short summary>

<Detailed multi-line body explaining the change. Wrap lines at ~72 characters. LIMITS: subject max 100 chars; body max 360 chars. Include why the change was made and any important notes. Separate subject and body by a single blank line. Do not include any extraneous commentary or markers. Use imperative mood.

Example:
refactor(ai): migrate providers to SDKs

Replaces direct API/CLI calls for Copilot and Gemini with SDK integrations.
This simplifies code, improves maintainability, and adds dynamic model
fetching. Updates .gitignore for geeto binaries.
`,
  'issue-prompt.md': `Generate a GitHub Issue title and body from this description.
IMPORTANT: Always write in English regardless of the input language.
Output ONLY in this exact format (no extra markers):

TITLE: <concise issue title, max 72 chars>

BODY:

## Description

<clear description of the issue>

## Expected Behavior / Goal

<what should happen or what is the goal>

## Additional Context

<any relevant details>
`,
  'issue-review.with-context.prompt.yml': `messages:
  - role: system
    content: >+
      PROJECT CONTEXT (short):
      Name: geeto
      Type: Node.js/TypeScript CLI toolkit integrating AI providers and Git workflows.
      Layout:
      - \`src/\` TypeScript sources (api, cli, core, utils, workflows)
      - \`lib/\` compiled JS used by the CLI
      - \`.github/workflows/\` contains CI workflows; \`auto-add-ai-label-on-open.yml\` runs AI assessments on new issues.
      - \`README.md\` is full documentation.

      GUIDELINES for using this context:
      - Use this short context to ground AI replies about repository behavior, conventions, and where code lives.
      - Prefer short labels: \`bug\`, \`feature\`, \`docs\`, \`usage\`, \`help\`, \`tool\`, \`question\`.
      - Keep public issue comments concise; include structured sections (Type, Assessment, Details, Suggested labels, Questions, Next steps, Summary).

      Presentation & tone:
      - Start with a friendly reply that feels personal.
      - Explain findings in a logical, step-by-step way (use numbered or short bullet steps) so readers can follow troubleshooting or implementation advice.
      - End with a short closing summary that restates the recommended next step(s).

      Off-topic handling:
      - If the issue is clearly outside this repository's scope (e.g., asking about unrelated frameworks, third-party services not integrated here, or general programming homework), respond with a short, polite nudge explaining it's off-topic and point to the right resources.
      - Use a light, slightly witty tone (a gentle "disindir") but never rude or insulting. Always be helpful: offer where to ask instead (Stack Overflow, relevant project, or documentation) and include a link to \`CONTRIBUTING.md\` and \`README.md\` for repo-specific guidance.
      - Suggested labels to add when off-topic: \`off-topic\`, \`needs-info\`, \`question\`.
      - Example (Indonesian): "Sepertinya masalah ini di luar lingkup repo ini — sepertinya terkait [tool X]. Coba tanyakan di repo/tool tersebut atau di Stack Overflow. Baca juga CONTRIBUTING.md untuk pedoman kontribusi."
      - Example (English): "This looks outside this repository's scope — it seems related to [tool X]. Please ask the maintainer/project for that tool or try Stack Overflow. See CONTRIBUTING.md for contribution guidelines."

  - role: system
    content: >+
      You are an experienced project issue reviewer. Use the PROJECT CONTEXT above when assessing issues so replies reference the repository layout and conventions.

      For the given issue ({{input}}), perform the following checks and provide a concise structured output.

      1) Categorize the issue as one of: \`bug\`, \`feature request\`, \`docs\`, \`usage/help\`, or \`other\`.

      2) For BUGs:
        - Determine severity: \`critical\` / \`high\` / \`medium\` / \`low\`.
        - Determine reproducibility: \`always\` / \`often\` / \`sometimes\` / \`rare\` / \`cannot reproduce\`.
        - Summarize 1–3 reproduction steps if present; otherwise state \`Reproduction steps: missing\`.
        - Suggest likely module/area involved (e.g., \`cli\`, \`installer\`, \`core\`, \`docs\`).
        - Recommend triage actions (request logs, version, minimal repro, or small PR/patch).

      3) For FEATURE REQUESTs:
        - Summarize the feature goal and benefit in one sentence.
        - Propose short acceptance criteria (1–3 items).
        - Estimate implementation complexity: \`low\` / \`medium\` / \`high\`.

      4) For ALL issues:
        - If relevant, extract a brief \`How to use (from README):\` block (2–6 commands) to help reproduce or test, but keep it short.
        - Ask up to 3 direct QUESTIONS if information is missing.
        - Suggest 1–3 short labels (single words) such as \`bug\`, \`feature\`, \`docs\`, \`usage\`, \`help\`, \`tool\`.

      5) Format output in the following structured sections (concise and clear):
        - \`Type:\` (bug / feature / docs / usage / other)
        - \`Assessment:\` (for bugs: severity & reproducibility; for features: goal & complexity)
        - \`Details:\` (reproduction steps, modules implicated, brief README excerpt if relevant)
        - \`Suggested labels:\` (list of short labels)
        - \`Questions:\` (0–3 short questions if needed)
        - \`Next steps:\` (3 brief actions for triage or implementation)
        - \`Summary:\` one-sentence final summary

      6) Language:
        - Answer in the same language as the issue. If the issue is written in Indonesian, answer in Indonesian. If the issue is written in English, answer in English.

      7) Limit output: keep it concise (max ~300 words), use simple markdown, and include short examples when helpful.

  - role: user
    content: '{{input}}'
model: openai/gpt-4o-mini
modelParameters:
  max_tokens: 700
  temperature: 0.2

testData: []
evaluators: []
`,
  'pr-prompt.md': `Generate a Pull Request title and body from this git diff.
Output ONLY in this exact format (no extra markers):

TITLE: <concise PR title, max 72 chars, imperative mood>

BODY:

## Summary

<1-2 sentence summary of what this PR does>

## Changes

<bullet list of key changes>
`,
  'release-notes-prompt.md': `You are a release notes writer. Given a list of git commit messages, generate user-friendly release notes in {{langLabel}}. Output ONLY the release notes content (no title/heading, no version number, no date — those are added separately).

Rules:

- Start with "### What's New?" as the top-level section
- Group changes into subsections: "#### New Features", "#### Bug Fixes", "#### Other Improvements"
- Only include subsections that have items (skip empty ones)
- Use simple, non-technical language that end users can understand
- Each item should be a bullet point starting with "-"
- Strip conventional commit prefixes (feat:, fix:, chore:, etc.)
- Keep it concise but informative
- If there are breaking changes, add a "#### Breaking Changes" subsection at the top
- Do NOT include commit hashes or author names

Formatting (follow EXACTLY — this is markdownlint-compliant):

- Always put ONE blank line after EVERY heading (### or ####) before the first bullet
- Always put ONE blank line after the last bullet in a section before the next #### heading
- Never have more than one consecutive blank line
- Example output:

### What's New?

#### New Features

- Feature description here
- Another feature

#### Bug Fixes

- Fix description here

#### Other Improvements

- Improvement here
`,
  'repo-description-prompt.md': `Analyze this README and write a short GitHub repo description (max 150 chars). Concise, informative. Output ONLY the text, no quotes.
`,
}
