/**
 * Auto-generate embedded prompts module from prompts/ directory.
 * Run: bun scripts/generate-prompts.ts
 *
 * This bakes prompt text into src/utils/prompts-embedded.ts so compiled
 * binaries can load prompts without the filesystem prompts/ folder.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dir, '..')
const PROMPTS_DIR = path.join(ROOT, 'prompts')
const OUTPUT_FILE = path.join(ROOT, 'src', 'utils', 'prompts-embedded.ts')

const files = readdirSync(PROMPTS_DIR)
  .filter((f) => f.endsWith('.md') || f.endsWith('.yml'))
  .sort()

let output = '// Auto-generated by scripts/generate-prompts.ts — DO NOT EDIT\n'
output += '// Regenerate: bun scripts/generate-prompts.ts\n\n'
output += 'export const EMBEDDED_PROMPTS: Record<string, string> = {\n'

for (const file of files) {
  const content = readFileSync(path.join(PROMPTS_DIR, file), 'utf8')
  const escaped = content.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('${', '\\${')
  output += `  '${file}': \`${escaped}\`,\n`
}

output += '}\n'

writeFileSync(OUTPUT_FILE, output, 'utf8')
console.log(`✓ Generated ${files.length} embedded prompts → src/utils/prompts-embedded.ts`)
